version: '2'
services:
  coalition_technologies:
    container_name: coalition_technologies
    image: lorisleiva/laravel-docker
    command: php /var/www/artisan serve --host=0.0.0.0 --port=4001
    ports:
      - 4001:4001
    volumes:
    - ./:/var/www/
    depends_on:
      - database
    environment:
      - DB_HOST=database
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - coalition-network

  database:
    image: mysql:5.7
    volumes:
      - "./data/mysql:/var/lib/mysql"
    command: [
      'mysqld',
      '--character-set-server=utf8',
      '--collation-server=utf8_general_ci'
    ]
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - coalition-network


  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - coalition-network
    depends_on:
      - database

volumes:
  mysql_data:
networks:
  coalition-network:
